# Generated by Django 2.2 on 2019-04-15 09:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('djangomysql', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookinfo',
            managers=[
                ('bookManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
